name: LP
version: 1.1.9.6 - hotfix
main: levelpoints.lp.LP
authors: [Zoon20X]
description: This is a Leveling Plugin
website: play.venturescraft.net

softdepend: [PlaceholderAPI]  # This can use placeholder api for some placeholders

commands:
  lps:
    usage: /<command>
  levelpoints:
    usage: /<command>
permissions:
  lp.*:
    description: Gives players all Commands
    default: op
    children:
      lp.admin.*:
        default: op
        lp.admin.give:
          default: op
        lp.admin.remove:
          default: op
        lp.admin.reload:
          default: op
      lp.player:
        default: not op
      lp.booter:
        default: not op